create or replace TABLE SPOTIFY_TRACKS_GOLD (
	ARTIST VARCHAR(16777216),
	ALBUM_NAME VARCHAR(16777216),
	TRACK_COUNT NUMBER(18,0),
	AVG_TRACK_POPULARITY NUMBER(38,6),
	MAX_TRACK_POPULARITY NUMBER(38,0),
	AVG_DURATION_MINUTES NUMBER(38,2),
	SHORT_TRACKS NUMBER(13,0),
	MEDIUM_TRACKS NUMBER(13,0),
	LONG_TRACKS NUMBER(13,0),
	FIRST_RELEASE_DATE DATE,
	LAST_RELEASE_DATE DATE,
	LAST_LOADED_AT TIMESTAMP_LTZ(9)
);