-- 02_tables_views.sql
-- Main tables and example views.

USE DATABASE SPOTIFY_ETL_DB;
USE SCHEMA PUBLIC;

-- Main curated table (13 columns)
CREATE OR REPLACE TABLE SPOTIFY_TRACKS (
  TRACK_ID        STRING,
  TRACK_NAME      STRING,
  ARTIST_NAME     STRING,
  ALBUM_NAME      STRING,
  ALBUM_ID        STRING,
  DURATION_MS     NUMBER,
  POPULARITY      NUMBER,
  EXPLICIT        BOOLEAN,
  RELEASE_DATE    STRING,
  DANCEABILITY    FLOAT,
  ENERGY          FLOAT,
  LIVENESS        FLOAT,
  TEMPO           FLOAT
);

-- Staging / raw table with same structure
CREATE OR REPLACE TABLE SPOTIFY_TRACKS_RAW
  LIKE SPOTIFY_TRACKS;

-- Silver / analytics-ready table
CREATE OR REPLACE TABLE SPOTIFY_TRACKS_SILVER AS
SELECT
  TRACK_ID,
  TRACK_NAME,
  ARTIST_NAME,
  ALBUM_NAME,
  DURATION_MS,
  ROUND(DURATION_MS / 60000.0, 2) AS DURATION_MINUTES,
  POPULARITY,
  RELEASE_DATE
FROM SPOTIFY_TRACKS
WHERE TRACK_ID IS NOT NULL;

-- Example views

-- 1) Data quality view: tracks with missing critical fields
CREATE OR REPLACE VIEW VW_SPOTIFY_DQ AS
SELECT *
FROM SPOTIFY_TRACKS
WHERE TRACK_NAME IS NULL
   OR ARTIST_NAME IS NULL
   OR ALBUM_NAME IS NULL;

-- 2) Top 10 tracks by popularity (simple example)
CREATE OR REPLACE VIEW VW_SPOTIFY_TRACKS_10 AS
SELECT
  TRACK_NAME,
  ARTIST_NAME,
  POPULARITY
FROM SPOTIFY_TRACKS
ORDER BY POPULARITY DESC
LIMIT 10;

-- 3) Example "gold" view for reporting
CREATE OR REPLACE VIEW VW_SPOTIFY_TRACKS_GOLD AS
SELECT
  TRACK_NAME,
  ARTIST_NAME,
  ALBUM_NAME,
  DURATION_MINUTES,
  POPULARITY,
  RELEASE_DATE
FROM SPOTIFY_TRACKS_SILVER;