-- 03_tasks.sql
-- Snowflake tasks to automate loading and transformation.

USE DATABASE SPOTIFY_ETL_DB;
USE SCHEMA PUBLIC;

-- 1) Task: load data from S3 stage into SPOTIFY_TRACKS
CREATE OR REPLACE TASK TASK_LOAD_SPOTIFY_TRACKS
  WAREHOUSE = SPOTIFY_WH
  SCHEDULE = 'USING CRON 0 * * * * America/Denver'  -- every hour
AS
COPY INTO SPOTIFY_TRACKS
  FROM @SPOTIFY_S3_STAGE
  FILE_FORMAT = (FORMAT_NAME = SPOTIFY_CSV_FORMAT)
  PATTERN = '.*\.csv'
  ON_ERROR = 'CONTINUE';

-- 2) Task: refresh SPOTIFY_TRACKS_SILVER from SPOTIFY_TRACKS
CREATE OR REPLACE TASK TASK_SPOTIFY_RAW_TO_SILVER
  WAREHOUSE = SPOTIFY_WH
  SCHEDULE = 'USING CRON 15 * * * * America/Denver'  -- 15 min after load
AS
CREATE OR REPLACE TABLE SPOTIFY_TRACKS_SILVER AS
SELECT
  TRACK_ID,
  TRACK_NAME,
  ARTIST_NAME,
  ALBUM_NAME,
  DURATION_MS,
  ROUND(DURATION_MS / 60000.0, 2) AS DURATION_MINUTES,
  POPULARITY,
  RELEASE_DATE
FROM SPOTIFY_TRACKS
WHERE TRACK_ID IS NOT NULL;

-- Enable tasks
ALTER TASK TASK_LOAD_SPOTIFY_TRACKS RESUME;
ALTER TASK TASK_SPOTIFY_RAW_TO_SILVER RESUME;

-- Check task status
SHOW TASKS;