-- 04_resource_monitor.sql
-- Optional: monitor warehouse credit usage.

CREATE OR REPLACE RESOURCE MONITOR SPOTIFY_ETL_MONITOR
  WITH CREDIT_QUOTA = 10
  TRIGGERS ON 80 PERCENT DO NOTIFY
           ON 100 PERCENT DO SUSPEND;

ALTER WAREHOUSE SPOTIFY_WH
  SET RESOURCE_MONITOR = SPOTIFY_ETL_MONITOR;