-- Create and configure warehouse used by this project
USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE WAREHOUSE SPOTIFY_WH
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Warehouse for Spotify ETL demo';

GRANT USAGE ON WAREHOUSE SPOTIFY_WH TO ROLE ACCOUNTADMIN;

-- Convenience defaults
USE WAREHOUSE SPOTIFY_WH;
USE DATABASE SPOTIFY_ETL_DB;
USE SCHEMA PUBLIC;